apiVersion: v1
kind: Service
metadata:
  name: course-tracker-service
  namespace: default
  labels:
    app: course-tracker
spec:
  selector:
    app: course-tracker
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort